### ISSUE TITLE
volume mounts negate entrypoint copy of jars to libs folder

### ISSUE THREAD

**Issue by moabu** [JanssenProject/docker-jans-auth-server#7]
Since the volume mount sets the permission of the uncreated folder `/opt/jans/jetty/jans-auth/custom/libs/` , the entrpoint script becomes unable to copy [twillo](https://github.com/JanssenProject/docker-jans-auth-server/blob/master/scripts/entrypoint.sh#L23) and [jsmpp](https://github.com/JanssenProject/docker-jans-auth-server/blob/master/scripts/entrypoint.sh#L23) to  `/opt/jans/jetty/jans-auth/custom/libs/` due to permission resteriction. 

```
cp: can't create '/opt/jans/jetty/jans-auth/custom/libs/twilio.jar': Permission denied
```

Example mount:

```yaml
        volumeMounts:
        - mountPath: /opt/jans/jetty/jans-auth/custom/libs/jose4j.jar
          name: jose4jjar
          subPath: jose4j.jar
      volumes:
      - configMap:
          defaultMode: 420
          name: jose4j
        name: jose4jjar
```

Instead the folder `/libs` should be created in the `Dockerfile` which restricts the permission to the mounted file.
